### ISSUE TITLE
"Block 3rd party cookies" support

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#267] opened 2016-11-24 18:09 UTC
Once I log in and then refresh the page, I am no longer logged in. I suspect it has to do with blocking third party cookies. Third party cookies are a serious privacy issue and I am not willing to enable them.

**Comment by povrazor** [comment] 2016-11-24 18:30
Hmm. Well it's not 3rd party, but the key cookie is on a different origin (`api.ldjam.com` vs `ldjam.com`). Are you able to whitelist `api.ldjam.com`?

**Comment by karai17** [comment] 2016-11-24 18:32
api.ldjam.com is already white listed it seems. what's being blocked is jam.vg.

![image](https://cloud.githubusercontent.com/assets/590332/20607912/c553bf6c-b252-11e6-8088-b5a0886de360.png)

![image](https://cloud.githubusercontent.com/assets/590332/20607915/cfac69d2-b252-11e6-84d6-cdbc92910c5f.png)

**Comment by povrazor** [comment] 2016-11-24 18:36
Ah okay. `Jam.vg` doesn't require any cookies (at least not on my end). If they're being set, it's probably CloudFlare. They do set one for their own silliness (DDOS protection and such).

If `api.ldjam.com` cookies are allowed, then you should stay logged in.

I'm guessing what happened is you closed the browser. I forgot that the `api.ldjam.com` cookie is in Session Only mode, which expires upon the browser closing.

**Comment by karai17** [comment] 2016-11-24 18:37
Nyet, I simply F5 the page.

**Comment by povrazor** [comment] 2016-11-24 18:37
Weird. The only cookie that matters is `api.jammer.vg`. What browser?

**Comment by karai17** [comment] 2016-11-24 18:38
Latest Chrome on Fedora 24.

**Comment by povrazor** [comment] 2016-11-24 18:39
What plugin is purging your cookies?

**Comment by karai17** [comment] 2016-11-24 18:41
I just have third part cookies in Chrome itself disabled. Privacy Badger doesn't seem to be showing any conflicts, nor does uBlock Origin.

**Comment by povrazor** [comment] 2016-11-24 18:43
Ah I see. That's built in to Chrome. Okay, I'll have a look.

**Comment by karai17** [comment] 2016-11-24 18:45
![image](https://cloud.githubusercontent.com/assets/590332/20608105/aff2b798-b254-11e6-9528-e2e14765cc7f.png)

**Comment by povrazor** [comment] 2016-12-03 07:48
I ran in to another user that had troubles doing anything. It turns out it was caused by a very aggressive work firewall. 

So, moving the API to the domain directly might be necessary for best compatibility. :(

**Comment by karai17** [comment] 2016-12-03 08:45
How do other websites manage subdomains and cdns in that case?

**Comment by povrazor** [comment] 2016-12-03 08:55
You can make cookies that are accessible by your subdomains. I was hoping to get away with isolating it to the API subdomain only.

**Comment by povrazor** [comment] 2017-05-09 05:06
#800 and #275.

**Closed by povrazor** 2017-05-09 05:06 UTC
Labels: enhancement, server
