### ISSUE TITLE
LD38 Games showing up in LD39 Games Tab

### ISSUE THREAD

**Issue by chronosv2** [ludumdare/ludumdare#1046] opened 2017-07-18 04:26 UTC
![image](https://user-images.githubusercontent.com/7937878/28300756-96978436-6b4f-11e7-8415-da52455ca868.png)
Viewing the "Games" tab for LD39 (which should currently be empty, I think) is showing the list of games, post-judgement, from LD38.

**Comment by local-minimum** [comment] 2017-07-25 08:00
Specifically, it seems like the `https://api.ludumdare.com/vx/node/feed/32802/grade-01-result+reverse/item/game/jam?limit=12` request, which is the correct uri, returns the wrong data.

**Comment by local-minimum** [comment] 2017-07-25 08:02
Or perhaps it is actually wrong uri in the `grade-01-result+reverse` bit since it shouldn't yet show results...but `32802` is the correct node for LD39.

**Comment by sgstair** [comment] 2017-07-25 08:05
I have a proposed fix for this in pull request #1061 
My assertion is the problem is only that the query doesnt include the "parent" method (only grade-01-result+reverse) - It seems like the filtering code may have been copied on top of the game code at some point and that detail was lost.

**Closed** 2018-05-20 19:54 UTC
Labels: bug, to be closed
