### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#1151] opened 2017-08-04 17:59 UTC
I find it very frustrating when someone gives me feedback, I can't ask for more information or ask them if a patch fixes their bug. It would be very handy to have notifications for @mentions in comments so there can be dialog about an issue or general discussion instead of only having one-off responses.

**Comment by povrazor** [comment] 2017-08-04 19:13
Duplicate of #183

**Closed by povrazor** 2017-08-04 19:13 UTC
