### ISSUE TITLE
Make game pages say which event it's from (and wether the game is Jam/Compo )

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1473] opened 2017-12-05 21:27 UTC
> (21:17:10) Hegemege: also noticed that there's nowhere on the game page which event it was produced for

**Comment by mikekasprzak** [comment] 2018-05-26 18:21
I'm pretty sure I ran in to a duplicate of this, but they do say what event they belong to (just it's not very loud).
![jampag](https://user-images.githubusercontent.com/1570313/40579188-08e36546-60f0-11e8-9d6c-3ea609e5b4e0.png)

**Comment by zwrawr** [comment] 2018-05-26 18:28
Yea, the new navigation makes it very clear.
![screenshot from 2018-05-26 19-26-39](https://user-images.githubusercontent.com/18352787/40579235-e44b48fe-611a-11e8-90ed-9f5df7a370a8.png)

**Closed** 2018-05-26 21:26 UTC
Labels: duplicate, to be closed
