### ISSUE TITLE
The game list shows entries from old LDs after refreshing ("Featured Event" switches to "All Events")

### ISSUE THREAD

**Issue by Racso** [ludumdare/ludumdare#1481] opened 2017-12-06 00:02 UTC
Sometimes, the game list shows entries from old LDs after refreshing because "Featured Event" switches to "All Events". This is serious, I think, because people may waste time reviewing games from finished events.

Steps to reproduce:
- Open https://ldjam.com/games
- Press F5 a couple of times. At some point, the list will start showing entries from previous LDs.

**Comment by povrazor** [comment] 2017-12-06 00:12
Weird. You'll note the first filter says "All Events" instead of "Featured Event" when this happens.

**Comment by local-minimum** [comment] 2018-08-13 19:45
I can't reproduce this now. So I'll close this. If it keeps happening someone will open a new issue with a new guide to reproduce.

**Closed by local-minimum** 2018-08-13 19:45 UTC
Labels: duplicate
