### ISSUE TITLE
Theme voting - Sorting user's votes by time

### ISSUE THREAD

**Issue by Aurel300** [ludumdare/ludumdare#610] opened 2017-04-15 14:33 UTC
The votes displayed on the theme slaughter page are indeed my votes, but they are not in the correct order (as added by JavaScript when voting).

I think the fix is just a `ORDER BY timestamp DESC` here:
https://github.com/ludumdare/ludumdare/blob/master/src/shrub/src/theme/theme_idea_vote.php#L11

(I set up the work environment but I'm not sure if there is a "create test data" command for the database, so I couldn't test this)

**Comment by zwrawr** [comment] 2017-04-15 14:43
There isn't currently a way to generate test data, but #499 is about it

**Comment by povrazor** [comment] 2017-04-15 16:46
As mentioned in #611, `timestamp` isn't indexed, but `id` is. I've already committed the change.

However! This isn't going to work. The way we're populating the array returned by the API actually implicitly sorts them by the key.

```js
function _db_GetPair( &$st ) {
	$result = $st->get_result();
	$ret = [];
	while ($row = $result->fetch_array(MYSQLI_NUM)) {
		$ret[$row[0]] = $row[1];  // this here
	}
	return $ret;
}
```
So for the change to work, the above code needs to be tweaked to append rather than implicitly insert sort.

**Comment by Aurel300** [comment] 2017-04-15 16:50
Would it be preferable to add another method (e.g. `_db_GetOrdered`) to use for this? In order to not break any other code that might rely on the key ordering.

**Comment by povrazor** [comment] 2017-04-15 16:52
Yes, I was just about to say that. Adding a `_db_GetPairUnsorted` called by `db_QueryFetchPairUnsorted`, and adjusting the the theme call to use it.

**Comment by Aurel300** [comment] 2017-04-15 17:04
Now `_db_GetPairUnsorted` and `db_QueryFetchPairUnsorted` seem badly named, cause the key is ignored :smile:

**Comment by povrazor** [comment] 2017-04-15 17:09
It actually wont work without the keys. See my comment.

**Comment by povrazor** [comment] 2017-04-16 10:23
For an update on #611.

* I was wrong about the sorting server side. Chrome's `preview` view when you look at incoming data coming in via XHR requests is sorted, but if you click the next tab (`response`) you can clearly see the data sorted in whichever order you choose.
* The cause of the awkward display order is something on the JavaScript side. I.e. `src/com/content-event/event-slaughter.js` is where this happens

**Comment by Aurel300** [comment] 2017-04-16 12:58
Ah, I think I found it.

https://github.com/ludumdare/ludumdare/blob/master/src/com/content-event/event-slaughter.js#L44

```js
'recent': Object.keys(r.votes).slice(Start).reverse()
```

I don't know if `state.recent` is cached client-side. If not, then `Start` always ends up equal to `0`. Maybe when renavigating to the page multiple times, without actually reloading?

Either way, `Object.keys()` actually sorts the keys:

```js
var a = [];
a["2"] = "foo";
a["3"] = "bar";
a["1"] = "boo";
console.log(Object.keys(a)); // outputs: ["1", "2", "3"]
```

String keys actually get cast to int:

```js
var a = [];
a["100"] = "foo";
a["150"] = "bar";
a["50"] = "boo";
console.log(a[150]); // outputs: "bar"
console.log(a); // outputs: [undefined × 49, "boo", undefined × 49, "foo", undefined × 49, "bar"]
```

So even iterating over keys doesn't help:

```js
for (let key in a){
    console.log(key);
}
// outputs: 50, 100, 150
```

Not sure how to solve this, unless we change the format passed by the API.

**Comment by povrazor** [comment] 2017-04-16 13:03
Good work. :smile:

I believe `recent` is not cached client side. Rather, it gets populated during load of the page. And while you're voting, new entries get added. When the page is refreshed, because you could theoretically be voting on multiple devices (your PC and your phone), we just assume we need a fresh copy of your recent theme list, and request the whole list again.

**Comment by povrazor** [comment] 2017-04-16 13:19
Actually naw, it looks like both of those are for arrays. I think what you want is to manually build that list using a `for in` loop.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

You can be a little wasteful here, iterating the entire list (since there will only every be a couple thousand entries max). You can use this as your reference:

```
Object.keys(r.votes).slice(Start).reverse()
```
In essence, the idea was to take the last several items on the list (wherever Start is supposed to end up), and add them in reverse order.

**Comment by Aurel300** [comment] 2017-04-16 13:29
The problem is, the server supplies a JSON like this: 

```js
{
  "caller_id": <some id>,
  "status": 200,
  "votes": {
    "<theme 1 id>": <theme 1 vote>,
    "<theme 2 id>": <theme 2 vote>,
    …
    "<theme N id>": <theme N vote>
  }
}
```

The `votes` object is not sorted, it is passed in the order we set server-side. But, it goes through a JSON parser. Which implicitly sorts the array according to the keys.

```js
var obj = JSON.parse('{"votes":{"2":"foo","3":"bar","1":"boo"}}');
console.log(obj.votes); // outputs: Object {1: "boo", 2: "foo", 3: "bar"}
```

One possible solution is to give the keys a prefix server-side:

```js
var obj = JSON.parse('{"votes":{"t2":"foo","t3":"bar","t1":"boo"}}');
console.log(obj.votes); // outputs: Object {t2: "foo", t3: "bar", t1: "boo"}
```

**Comment by povrazor** [comment] 2017-04-16 13:45
Shoot. You're right.

http://stackoverflow.com/a/4515863/5678759

Actually even with a prefix we can't be sure the order will be correct.

Okay, so it looks like this needs to be changed to an actual array server side. That seems like the only way JavaScript will preserve the order when passed through `JSON.parse`.

In that case, `db_QueryFetchPair` can become `db_QueryFetch`. That should emit an array of objects with whatever the key names were (I'm guessing `id` and `theme`).

**Comment by povrazor** [comment] 2017-04-16 13:50
Here's roughly what hack-adding an event looks like.

![myevent](https://cloud.githubusercontent.com/assets/1570313/25071620/22e24002-228a-11e7-830b-e16c74d76af3.png)

That should create an event here:

http://ludumdare.org/my-event

**Comment by Aurel300** [comment] 2017-04-16 13:51
More relevant to #499, I'll look into that after this :)

**Comment by povrazor** [comment] 2017-04-16 13:59
Yep. Here's the part that you'll care about though. You need to then add a piece of metadata to say what theme voting mode the event is in .

![set-mode](https://cloud.githubusercontent.com/assets/1570313/25071643/b3cfb658-228a-11e7-85ea-8376a09f6fed.png)

* 0 - null
* 1 - Theme Suggestions
* 2 - Theme Slaughter

etc.

You'll have to populate the db some themes. There's a hard limit of 3 per user. It's supposed to be confugurable per event, but I'm not seeing that code anywhere. You probably want to make a couple users so you have enough data. You can logout using this.

http://api.ludumdare.org/vx/user/logout

**Closed** 2018-05-20 18:10 UTC
Labels: bug, enhancement
