### ISSUE TITLE
Smart Balance sudden plummeting

### ISSUE THREAD

**Issue by Devastus** [ludumdare/ludumdare#1889] opened 2020-04-23 16:08 UTC
Just noticed this happening:
![nekotchi_ratings_01](https://user-images.githubusercontent.com/25803613/80121206-ab12a000-8594-11ea-9e73-7a4c56904e1f.png)
After playing and rating a couple games more (~45min later):
![nekotchi_ratings_02](https://user-images.githubusercontent.com/25803613/80121212-acdc6380-8594-11ea-9296-9efe84579573.png)

Now, we've received more than enough ratings with the borderline 80 so it's not a big deal personally, but I thought to submit this as it's peculiar behaviour, especially since it was ratings **given, not received** that went over the 80 mark. 

I'm not knowledgeable enough of the codebase and the intricacies behind Smart Balance calculation, so I need to pose the question: is there possibly something intentional derailing the score or is it a bug?

Just to show, the entry is at https://ldjam.com/events/ludum-dare/46/nekotchi, and the Smart Balance has stayed in the -40 area after updates to ratings given and karma received from feedback.

**Comment by mikekasprzak** [comment] 2020-05-03 05:09
It looks like you caught the moment when I pushed a significant change to how the Smart filter worked.  The system now puts less impact on ratings given, and the majority is now on feedback. For now I'll call this "by design" and close it.

**Closed by mikekasprzak** 2020-05-03 05:09 UTC
