### ISSUE TITLE
Categories for next LD

### ISSUE THREAD

**Issue by BurgeeGames** [ludumdare/ludumdare#1002] opened 2017-05-22 20:45 UTC
I don't think I'm alone in this but for now let's assume I'm only speaking for myself.

The 'Mood' Category is too vague and confusing. In my opinion it should be replaced with 'polish' or 'quality' or something a bit more tangible. 

The 'Overall' category - why can we even vote on this?  Shouldn't 'overall' be an average of all of the other  categories? This is the one that makes the least sense to me.

Edit: Also wanted to add -

Comments should be anonymous.  

The feedback is too much on the 'friendly' side to the point where I didn't learn much about why my ratings weren't higher. Everyone wants to be nice so the reviewer gives them a nice review back.

But what about feedback friends and such? Well, LD could / should suggest to you a list of games that you should review - some of whom gave you feedback, some of whom are randomly chosen. This would ensure feedback receives feedback.  Not to mention coolness points would still work just fine for game sorting.

**Comment by zwrawr** [comment] 2017-05-22 20:58
Dupe of #832.  You should add your views to that issue and close this one. :)

**Closed** 2017-05-22 21:09 UTC
