### ISSUE TITLE
Spinner is not removed in the user page

### ISSUE THREAD

**Issue by JortHub** [ludumdare/ludumdare#748] opened 2017-04-23 10:47 UTC
When my user page is loading the spinner doesn't stop. In the Network tools Chrome says the webpage isn't loading anything and the page looks like it's fully loaded. I have reloaded the site a few times, but the spinner still stays on the screen. The spinner also remains when I emulate other browsers.

A printscreen of the site:
![ld](https://cloud.githubusercontent.com/assets/10116429/25312754/3d204832-2821-11e7-95e5-7165663ebc7f.png)

This might also be useful:
![ld2](https://cloud.githubusercontent.com/assets/10116429/25312793/e85685fe-2821-11e7-9a32-318c822f2cbb.png)

And a profile when loading the site:
[Profile.zip](https://github.com/ludumdare/ludumdare/files/949619/Profile.zip)

**Browser:** Chrome (57.0.2987.133)
**OS:** Windows 10 1(0.0.14393)

**Comment by zwrawr** [comment] 2017-04-23 10:51
Okay i think i know what the problem is. What happens if you click the "join event" button and make a draft of your game submission.

**Comment by JortHub** [comment] 2017-04-23 10:52
When I create a game it is removed

**Comment by zwrawr** [comment] 2017-04-23 11:00
Can you click this link and paste the results here https://api.ldjam.com/vx/node/get/9420?pretty

**Comment by JortHub** [comment] 2017-04-23 11:33
Sure:
`{
    "status": 200,
    "caller_id": 9420,
    "node": [
        {
            "id": 9420,
            "parent": 2,
            "superparent": 0,
            "author": 9420,
            "type": "user",
            "subtype": "",
            "subsubtype": "",
            "published": "2017-03-27T18:13:49Z",
            "created": "2017-03-27T18:13:49Z",
            "modified": "2017-03-27T18:13:49Z",
            "version": 9396,
            "slug": "jortvd",
            "name": "JortvD",
            "body": "",
            "path": "/users/jortvd",
            "parents": [
                1,
                2
            ],
            "games": 1,
            "articles": 0,
            "posts": 0,
            "meta": [],
            "link": [],
            "love": 0
        }
    ]
}`

**Comment by zwrawr** [comment] 2017-04-23 11:42
Looks to be a similar issue, we need to add a check to make sure you have posts before we try to show them. In the mean time if you make a post then your feed should work.

**Comment by zwrawr** [comment] 2017-04-23 12:01
Okay, i can reproduce this with a new account, http://prntscr.com/eztex8 Will  get to work on a fix.

**Comment by zwrawr** [comment] 2017-04-27 00:33
@JortHub is this still an issue for you? I think this is fixed

**Comment by JortHub** [comment] 2017-04-30 09:15
The spinner on the top is gone, but there is a new spinner under the feed tab (on my user page). I think this spinner appears when your feed is empty, but I haven't tested that theory.

**Comment by povrazor** [comment] 2017-04-30 13:43
Yes, from what I've seen this happens when the feed is empty.

I've had a few people come to me confused about this, so if someone could look in to this, it would be much appreciated.

**Comment by local-minimum** [comment] 2017-05-31 20:47
I think line 39 of `content-common\common.js` is the culprit:

```js
				if ( node && node.slug ) {
```
or similar because `node`  is probably empty list and would fail truthiness of `node` is guess. The else needs to check if whatever is actually `undefined` and only then show spinner. That's my bet.

**Comment by local-minimum** [comment] 2017-06-01 20:37
Having looked around more I must say I'm quite confused. When the feed on a user page is requested, the `timeline.js` is called (`getFeed`), but that callback/`then`  causes `loaded` to be set `true` even if there's no posts. Still this doesn't remove the spinner/`ContentLoading`  if there are no posts...

**Comment by sgstair** [comment] 2017-07-20 10:05
After digging around it for a while I think I understand what is going on.
timeline.js has this error:
>		else if ( feed && feed.length == 0 ){
>			ShowFeed.push(<ContentCommon><h1>Sorry, there are no {props.types[0]}</h1></ContentCommon>);
>		}
But ContentCommon, without the appropriate properties (A node.slug, as @local-minimum noticed), will just emit a 
>    &lt;ContentLoading />

Compare this to the output of ContentGames in this situation which looks like:
>			return (
>				<ContentCommon {...props}>
>					<ContentCommonBodyTitle href={""} title={"No Games!"} />
>					<ContentCommonBody>Sorry, there are no published games yet</ContentCommonBody>
>				</ContentCommon>
>			);

I'll work on and verify a fix, but should sleep now :)

**Comment by sgstair** [comment] 2017-07-20 16:39
(fix submitted to my repo, will be in a pull request soon.)

**Comment by zwrawr** [comment] 2017-12-11 07:33
User pages and the router was rewritten, this shouldn't be an issue any more.
Can be closed.

**Comment by povrazor** [comment] 2017-12-11 18:05
User pages don't 404 correctly (they're missing the 404 endpoint in their router), but yeah that's a different issue.

**Closed by povrazor** 2017-12-11 18:05 UTC
Labels: bug
