### ISSUE TITLE
Markdown: Add "spoilers" support

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#809] opened 2017-04-28 22:26 UTC
> Local Minimum‏ @Local_Minimum
>
> what markdown engine does ldjam use/can it be made to support spoilers? hidden text that show with user interaction.
> Would be awesome on game submit & comment to give extra instructions that may spoil content or discuss content more freely

**Comment by povrazor** [comment] 2017-04-28 22:28
I don't know what other markdown engines use for spoilers, but I quite like this idea.

**Comment by zwrawr** [comment] 2017-04-28 23:06
Totally possible.
Its made trickier by the fact that were not using es6 for the markdown engine. But the youtube embed can be used as an example on how to switch out content based on user interaction.

**Comment by povrazor** [comment] 2017-04-29 00:30
I found one mention of Spoiler syntax. It works similar to blockquotes.

```
!> This text is a spoiler
!> Don't spoil me bro
```
http://stackoverflow.com/a/32183830/5678759

**Comment by povrazor** [comment] 2017-04-29 00:40
Another spoiler syntax looks like this.

```
>! this is a spoiler
> ! this is also a spoiler
```
https://meta.stackexchange.com/a/72878

The link above demonstrates it. I don't think that I like that hovering reveals it (it's mobile friendly).

I'm not entirely sure what I think of this alternative (i.e. `!` after the blockquote). I think I prefer the syntax with it before the blockquote, so everything on the block quoted line can just be assumed to be in the block.

**Comment by local-minimum** [comment] 2017-04-29 06:49
I saw that linestart `!>` right before falling asleep yesterday and it seems reasonable and doable. That you can do other formatting is important, because you may want to say something like

```
!> Pressing `X` on the tree trunk will make the squirrel throw a nut on you
```

Checked the marked.js code and I almost partially think I understand how it would be done on the js-side. Then it's just css for the effect, I guess?

Inline spoiling isn't really as needed, and could be added at a later date if people request it by some similar styled `!!>spoiler!!>` thingy.

**Comment by local-minimum** [comment] 2017-04-29 07:33
I made what I think are the needed changes here:

https://github.com/ludumdare/ludumdare/compare/master...local-minimum:patch-1

But I don't know how to test them really (and since there's no css to go with it, they won't really have an effect..

Should I pull request them?

**Comment by zwrawr** [comment] 2017-04-29 07:44
Definitely PR them! If you want to style them then [here](/ludumdare/ludumdare/blob/master/src/com/content-common/common-body-markup.less) would be a good place to do it.

**Comment by local-minimum** [comment] 2017-04-29 07:47
That CSS was above my skills but I imagine something like start with black text och black background and then default to common style when clicked on or something.

**Comment by povrazor** [comment] 2017-04-29 14:48
Check out the toolchain setup instructions here:

https://github.com/ludumdare/dairybox

Like I mentioned in the PR, the markdown parser is a scary bit of code. Every output bug in blog posts, user pages, game pages, and comments live there. Little tweaks of a single line I'm more willing to merge in untested. But there's some scary stuff in that file that has consequences across the site.

It's okay if it takes you some time to get up to speed with the tools. We'll gladly help you along.

**Comment by local-minimum** [comment] 2017-04-29 16:16
I'm not certain what is the best expected behavior here either:

```
!> Line A
!> Line B
```

Should showing spoiler line B be included in showing line A? Or should one spoil them separately?

You could imagine spoilers to be step-wise instructions like a walk-through, but at the same time you don't want to unspoil every single line if it is just one spoiler.

**Comment by povrazor** [comment] 2017-04-29 19:36
This is fine. If you want a 2nd spoiler block, you put a gap.

```
!> Spoiler 1
!> Spoiler 1

!> Spolier 2
```

Again, copying what blockquote does would give you this behavior.

**Comment by local-minimum** [comment] 2017-05-02 18:13
Allright, I hope my pull request now is up to speed. It copies the blockquote behaviour and then uses css for hover and focus to remove color that is blocking reading.

**Comment by povrazor** [comment] 2017-06-20 05:19
I think preliminary support is in for this.

**Comment by local-minimum** [comment] 2018-08-16 14:59
It works like the blockquote but both have some slight strangeness to them in that

```
!> line
next
```
Will include `next` with `line` so you would have to make

```
!> next

line
```
For it to work as expected. Same for blockquotes. But I really don't think we have to bother and just say this is solved.

**Comment by mikekasprzak** [comment] 2018-08-16 18:33
There's a related issue on the odd behavior of newline. If you compare us
to GitHub, the github way feels more natural.

**Comment by local-minimum** [comment] 2019-05-01 11:54
I'm gonna close this issue because it is confusing to have it open and open a new one for the next line behavior issue.

**Closed by local-minimum** 2019-05-01 11:54 UTC
Labels: enhancement, markdown, to be closed
