### ISSUE TITLE
https://ldjam.com doesn't load any content on iOS 8

### ISSUE THREAD

**Issue by ianh** [ludumdare/ludumdare#394] opened 2016-12-06 01:47 UTC
On my phone (an iPhone 5C running iOS 8.3) the ldjam website loads, but no content appears on it (it's just blank gray).

**Comment by povrazor** [comment] 2016-12-06 01:56
Odd. It appears to be working fine on my iPad. Are you on WiFi or cellular internet? Are you behind a work firewall?

**Comment by ianh** [comment] 2016-12-06 01:58
Thanks for the quick reply!  I'm using WiFi, no firewall.  It works fine on a laptop on the same network.

**Comment by povrazor** [comment] 2016-12-06 02:00
Hmm. I'm assuming you're using Safari (who doesn't on iOS)?

I'm going pull an old iPod Touch out of storage and get it charging. See if I can reproduce on that.

**Comment by ianh** [comment] 2016-12-06 02:05
Thanks!  Are you using any recent JavaScript features? (iOS 8.3 is kind of old.) One fix might be to load the page content even if JavaScript isn't working for whatever reason.

**Comment by povrazor** [comment] 2016-12-06 02:06
![img_20161205_210746](https://cloud.githubusercontent.com/assets/1570313/20910267/8e6fb214-bb2e-11e6-8269-3ae63b0a9f73.jpg)

Charging ...

**Comment by povrazor** [comment] 2016-12-06 02:07
The page doesn't work without JavaScript. It's basically web-app now. Once it loads it actually fetches the page data.

**Comment by ianh** [comment] 2016-12-06 02:19
Yeah, I probably should, but I figured I'd report this anyway in case there are other people using older devices who haven't (or can't) upgrade.  I can understand if you don't want to spend time on supporting old devices though!

**Comment by povrazor** [comment] 2016-12-06 02:21
Okay confirmed. I get a gray-screen on iOS 5.

And yes I'm using some modern JS/HTML5 features. It is worth trying to figure out what we're missing though, so we can pop up something and say "hey, you're phone is too old".

Android definitely has the advantage here, since Google separated the Chrome browser from the OS.

**Comment by povrazor** [comment] 2016-12-06 02:35
Calling for some help here. If somebody has access to an iOS device running an old OS, and the tools necessary to dump some logs, can I get a paste of what the errors are? Thanks!

**Comment by ajayyy** [comment] 2016-12-06 02:35
One of the few times Android is better with updates than iOS.

**Comment by ajayyy** [comment] 2016-12-06 02:37
@povrazor Looks like there is a developer mode on mobile safari but it requires a Mac. Here: https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

**Comment by povrazor** [comment] 2016-12-06 02:39
Yeah, there's a complicated way to make Chrome do it too.

https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

I'm hoping someone else has a setup handy, 'cause I don't. :)

**Comment by matthewvroman** [comment] 2016-12-06 03:04
@povrazor Here's the error I'm seeing. It's pretty vague. Running IOS7 Safari. 
<img width="976" alt="screen shot 2016-12-05 at 7 02 25 pm" src="https://cloud.githubusercontent.com/assets/1207382/20911557/8572d81e-bb1d-11e6-816a-d214ffaecd13.png">
<img width="981" alt="screen shot 2016-12-05 at 7 02 52 pm" src="https://cloud.githubusercontent.com/assets/1207382/20911556/8572ca0e-bb1d-11e6-9acf-263e4e6ed3f0.png">

**Comment by povrazor** [comment] 2016-12-06 03:38
Thanks @matthewvroman. You're right, it looks like the issue is history.

http://stackoverflow.com/a/6168151/5678759

Sounds like older iOS versions had some funny issues with History. And they must be now fixed as of iOS 9.

**Comment by povrazor** [comment] 2016-12-07 01:07
Marking this as wontfix right now, but leaving it open.

**Comment by povrazor** [comment] 2016-12-07 01:15
If anyone is listening, I could use a suggestion for a user-agent string to check for, to confirm it's an iOS version before iOS 9 (and not a Mac). I realize user-agents aren't ideal, but by design, most users should be unable to change their user-agent on an iOS device. 

Also, it shouldn't false-positive on 3rd party iOS browsers like Chrome and Opera (and whatever is out there).

On my end, I'm going to do the check from the PHP side, and emit a page, similar to the one emitted when you use Internet Explorer 10 and earlier.

**Comment by ajayyy** [comment] 2016-12-07 01:15
The iPhone 4 and below are stuck on iOS 7 forever. I agree this can be fixed later. And just for future reference, this answer looks like it might be easier to implement: http://stackoverflow.com/a/6499740/1985387

**Comment by povrazor** [comment] 2016-12-07 01:18
The problem is that I'm using hashes for for dialogs. In essence, URLs on the website support multi-tasking. Task1 is the main url (`https://ldjam.com/some/page`), and Task2 is the hash (`#tv/awesome-user`).

**Comment by ajayyy** [comment] 2016-12-07 01:20
Oh that's weird. It is really weird so many iOS versions have this bug.

**Comment by povrazor** [comment] 2016-12-07 01:22
I suppose alternatively I could disable history. I think history on Microsoft Edge is actually broken at the moment, so it wouldn't be a big deal.

**Comment by povrazor** [comment] 2016-12-07 01:30
If anybody is willing to look in to this (how to check for one of the broken iOS history versions), I can easily use that to wrap my calls to the history code.

The tricky part is that history is supported on older iOS versions, but replaceState doesn't work (some security exception or whatever). I'm not sure about pushState (you'll have to tell me).

**Comment by matthewvroman** [comment] 2016-12-07 01:31
What about using history.js instead of the default HTML5 history? The git repo claims to solve issues with older browsers such as mobile Safari.

https://github.com/browserstate/history.js/

**Comment by povrazor** [comment] 2016-12-07 01:40
`history.js` works around it by using hash, which as mentioned, I'm using for other things.

**Comment by lightblub** [comment] 2017-04-20 17:07
As a quick workaround it's possible to use window.onerror for this?

```js
window.onerror = function() {
  document.write('oh no! update your browser')
}
```

...perhaps putting this as a `<script>` tag _by itself_ on the page to be run before the potentially-breaking code.

**Comment by povrazor** [comment] 2017-04-20 18:09
That's a neat idea. I'm not sure of the consequences (we're using a VDOM, like React), but doing something on error isn't a bad idea.

**Comment by mikekasprzak** [comment] 2018-05-20 19:26
Closing this due to this being the only report of a broken legacy iOS version.

**Closed by mikekasprzak** 2018-05-20 19:26 UTC
Labels: bug, help wanted
