### ISSUE TITLE
Theme slaughter doesn't work in qutebrowser

### ISSUE THREAD

**Issue by Knowledge-soda** [ludumdare/ludumdare#1701] opened 2018-08-02 15:50 UTC
I mostly use vim-like web browser call qutebrowser.

At first when I tried to slaughter themes, my choices weren't showing. I thought that it would work if I "Join in Ludum Dare 42" but it just made things worse.
There is loading sign but it won't load at all (screenshot below).
![screenshot_ld](https://user-images.githubusercontent.com/7338903/43595164-4105b8ae-967c-11e8-8815-88abce36c9cb.png)

It works perfectly on Firefox.
My qutebrowser version info is:
```
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.9.0-7-amd64-x86_64-with-debian-9.5, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5
```

**Comment by local-minimum** [comment] 2018-08-03 08:04
Do you have a debug terminal for the browser where you can check the javascript console for error messages and if there are none, what happens to the xhr-reqests. Also, do you hit similar problems in if you use something like vimperator in Firefox?

**Comment by Knowledge-soda** [comment] 2018-08-03 14:23
I don't know much about web browsers, so I'm not sure which part of log is important. Here are log messages after initialisation:
```
16:11:58 DEBUG    misc       mainwindow:_update_overlay_geometry:300 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7fab207195e8>: PyQt5.QtCore.QRect(0, 854, 1601, 1)
16:11:58 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7fab210d34c8>
16:11:58 DEBUG    webview    browsertab:_set_load_status:692 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://ldjam.com/events/ludum-dare/42/theme'>: LoadStatus.loading
16:11:58 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('loading') (tab 0)
16:11:58 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_started() (tab 0)
16:11:58 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
16:11:58 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
16:11:58 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:11:58 DEBUG    webview    webview:acceptNavigationRequest:299 navigation request: url https://ldjam.com/events/ludum-dare/42/theme, type NavigationTypeReload, is_main_frame True
16:11:59 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:11:59 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'Ludum Dare 42 | ldjam.com'
16:11:59 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [constructor]
16:11:59 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'ldjam.com'
16:11:59 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchData]
16:11:59 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchUser]
16:11:59 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchRoot]
16:12:00 DEBUG    sql        sql:__init__:150 Preparing SQL query: "INSERT INTO History (atime, redirect, title, url) values(:atime, :redirect, :title, :url)"
16:12:00 DEBUG    sql        sql:run:168 Running SQL query: "INSERT INTO History (atime, redirect, title, url) values(:atime, :redirect, :title, :url)"
16:12:00 DEBUG    sql        sql:run:171 query bindings: {':atime': 1533305520, ':redirect': False, ':url': 'https://ldjam.com/events/ludum-dare/42/theme', ':title': 'ldjam.com'}
16:12:00 DEBUG    sql        sql:__init__:150 Preparing SQL query: "REPLACE INTO CompletionHistory (last_atime, title, url) values(:last_atime, :title, :url)"
16:12:00 DEBUG    sql        sql:run:168 Running SQL query: "REPLACE INTO CompletionHistory (last_atime, title, url) values(:last_atime, :title, :url)"
16:12:00 DEBUG    sql        sql:run:171 query bindings: {':title': 'ldjam.com', ':url': 'https://ldjam.com/events/ludum-dare/42/theme', ':last_atime': 1533305520}
16:12:00 DEBUG    sessions   sessions:save:289 Saving session _autosave to /home/jakov/.local/share/qutebrowser/sessions/_autosave.yml...
16:12:00 DEBUG    webview    browsertab:_set_load_status:692 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://ldjam.com/events/ludum-dare/42/theme'>: LoadStatus.success_https
16:12:00 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('success_https') (tab 0)
16:12:00 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_finished(True) (tab 0)
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured]
16:12:00 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:12:00 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'ldjam.com'
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchUser] caller_id:
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured] +
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchUser] Done:
16:12:00 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:12:00 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'ldjam.com'
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchNode]
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured] My Game(s):
16:12:00 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:12:00 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring only-modifier keyeevent.
16:12:00 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x1000023 / text: ''
16:12:00 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring, no text char
16:12:00 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: False, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7faaf49890d8>)
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured] 100971 was the last modified
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured] 100971 chosen as Focus
16:12:00 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] [fetchFeatured] -
16:12:00 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:12:00 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'ldjam.com'
16:12:00 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: None
16:12:00 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'Ludum Dare 42 | ldjam.com'
16:12:01 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://ldjam.com/events/ludum-dare/42/theme')) (tab 0)
16:12:01 DEBUG    webview    tabbedbrowser:on_title_changed:586 Changing title for idx 0 to 'Ludum Dare 42 | ldjam.com'
16:12:01 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] Loaded my Ideas and Themes
16:12:01 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] Potentially unhandled rejection [1] TypeError: Object.values is not a function
    at t.renderBody (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:338924)
    at t.render (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:341082)
    at renderComponent (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:7195)
    at rerender (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:1016)
    at https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:107505
    at x (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:107546)
    at g.when (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:111091)
    at _.run (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:112196)
    at e._drain (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:102606)
    at drain (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:102260)
16:12:01 DEBUG    js         shared:javascript_log_message:136 [https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1] Potentially unhandled rejection [2] TypeError: Object.values is not a function
    at t.renderBody (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:338924)
    at t.render (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:341082)
    at renderComponent (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:7195)
    at rerender (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:1016)
    at https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:107505
    at x (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:107546)
    at g.when (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:111091)
    at _.run (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:112196)
    at e._drain (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:102606)
    at drain (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:102260)
16:12:03 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7fab20719f78>
16:12:03 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
16:12:04 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:12:04 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring only-modifier keyeevent.
16:12:04 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x1000023 / text: ''
16:12:04 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring, no text char
16:12:04 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: False, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7faaf498c0d8>)
16:12:04 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: None
16:13:23 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7fab20719f78>
16:13:24 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:13:24 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring only-modifier keyeevent.
16:13:24 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x1000023 / text: ''
16:13:24 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring, no text char
16:13:24 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: False, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7faaf498c0d8>)
16:13:24 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: None
16:14:00 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7fab20719f78>
16:14:00 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
16:14:02 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:14:02 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring only-modifier keyeevent.
16:14:02 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x1000020 / text: ''
16:14:02 DEBUG    keyboard   basekeyparser:_debug_log:108 Ignoring, no text char
16:14:02 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: False, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7faaf498c0d8>)
16:14:03 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 No special binding found for shift+z.
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x5a / text: 'Z'
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 No match for 'Z' (added Z)
16:14:03 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <PyQt5.QtWidgets.QOpenGLWidget object at 0x7faaf498c0d8>)
16:14:03 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
16:14:03 DEBUG    misc       mainwindow:_update_overlay_geometry:300 new geometry for <qutebrowser.misc.keyhintwidget.KeyHintView win_id=0>: PyQt5.QtCore.QRect(0, 806, 147, 49)
16:14:03 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 No special binding found for shift+z.
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 Got key: 0x5a / text: 'Z'
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 Definitive match for 'ZZ'.
16:14:03 DEBUG    keyboard   basekeyparser:_debug_log:108 discarding keystring 'ZZ'.
16:14:03 DEBUG    commands   command:run:485 command called: quit ['--save']
16:14:03 DEBUG    commands   command:run:500 Calling qutebrowser.app.Quitter.quit(<qutebrowser.app.Quitter object at 0x7fab98d17e48>, True, None)
16:14:03 DEBUG    destroy    app:shutdown:709 Shutting down with status 0, session <object object at 0x7fab9a5d73d0>...
16:14:03 DEBUG    sessions   sessions:save:289 Saving session default to /home/jakov/.local/share/qutebrowser/sessions/default.yml...
16:14:04 DEBUG    prompt     prompt:shutdown:135 Shutting down with loops []
16:14:04 DEBUG    destroy    app:_shutdown:736 Stage 2 of shutting down...
16:14:04 DEBUG    destroy    app:_shutdown:742 Removing eventfilter...
16:14:04 DEBUG    destroy    mainwindow:_do_close:548 Closing window 0
16:14:04 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <qutebrowser.mainwindow.tabwidget.TabBar count=0>
16:14:04 DEBUG    ipc        ipc:shutdown:402 Shutting down IPC (socket 0x55598d4c10e0)
16:14:04 DEBUG    save       savemanager:save:96 Save of yaml-config requested - dirty False, save_on_exit False, is_exit True, force False -> False
16:14:04 DEBUG    save       savemanager:save:96 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True
16:14:04 DEBUG    save       savemanager:save:96 Save of command-history requested - dirty False, save_on_exit False, is_exit True, force False -> False
16:14:04 DEBUG    save       savemanager:save:96 Save of quickmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
16:14:04 DEBUG    save       savemanager:save:96 Save of bookmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
16:14:04 DEBUG    save       savemanager:save:96 Save of cookies requested - dirty False, save_on_exit False, is_exit True, force False -> False
16:14:04 DEBUG    destroy    app:_shutdown:772 Deactivating crash log...
16:14:04 DEBUG    destroy    app:_shutdown:782 Deactivating message handler...
16:14:04 DEBUG    destroy    app:_shutdown:785 Deferring QApplication::exit...
16:14:04 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: None)
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: 0
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: tab
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: hintmanager
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: 0
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: main-window
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: last-focused-main-window
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: last-visible-main-window
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: message-bridge
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: qtnetwork-download-manager
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: statusbar
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: status-command
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: tabbed-browser
16:14:04 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7fab21037dc8>
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: completion
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: mode-manager
16:14:04 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7fab2074f048>
16:14:04 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: prompt-container
16:14:04 DEBUG    destroy    app:exit:850 Now calling QApplication::exit.
```
I have no problems with Vimium on Firefox (even hotkeys work).

**Comment by local-minimum** [comment] 2018-08-05 12:17
Now the problem is figuring out what's the error causing thing at

`    at drain (https://ldjam.com/-/all.min.js?v=4300-cd3e22e:1:102260)`

(character 102260, all in one big line) in the minified version (all.min.js), unless you want to setup a full debug version of ldjam on your computer.

**Comment by mikekasprzak** [comment] 2018-08-10 05:16
![screenshot from 2018-08-10 01-13-12](https://user-images.githubusercontent.com/1570313/43939909-e3110b80-9c3a-11e8-838c-4009eba45ce4.png)

You might just need to update some part of your system. I had no problems with the `qutebrowser` in the Ubuntu 18.04 repos.

**Comment by Knowledge-soda** [comment] 2018-08-11 22:58
Well, I use Debian Stable which constantly has old packages so it is completely possible that new qutebrower doesn't have that problem.

**Comment by mikekasprzak** [comment] 2018-08-12 00:54
We are doing some bleeding edge stuff. Like, last I checked Internet Explorer didn't work. :wink:

**Closed** 2018-08-15 21:01 UTC
Labels: to be closed
