### ISSUE TITLE
Post refreshes when <3'd

### ISSUE THREAD

**Issue by pta2002** [ludumdare/ludumdare#460] opened 2016-12-08 15:18 UTC
This means that embedded media will reset!

**Comment by Ulydev** [comment] 2016-12-08 17:13
Just noticed this as well. I'll take a look at it.
I think it is due to the onLove event modifying the state and causing a rerender.

https://github.com/ludumdare/ludumdare/blob/master/src/com/content-post/post.js#L136

**Comment by Ulydev** [comment] 2016-12-08 18:46
fixed in c6269e1a27e41647edd9f9593b5cca83d60ef605

**Comment by povrazor** [comment] 2016-12-08 21:16
This is actually by design.

https://github.com/ludumdare/ludumdare/blob/master/public-api/vx/node.php#L213

The reason for this is to allow a level of interactivity for users that do not yet have accounts. Currently the event is targeted at developers, but this is one method for non-developers to be part of it.

For the sake of security though, anonymous love is limited to 1 love per node per IP address. It's also (at this time) the only thing you're allowed to do without an account.

It can technically be used to give your posts an extra Love, but as far as sorting and filtering is concerned, it just means we up the minimum.

For reference, Love has always worked this way, even on the old site. The minumum threshold before anything happened was 4 love. If "loving" does become a more common thing, this number will change.

**Comment by povrazor** [comment] 2016-12-08 22:06
It's also partially related to how the Markdown parser is being used. The YouTube video embedder (I'm assuming this was where the issue was found) isn't clever yet.

**Closed** 2016-12-09 01:19 UTC
Labels: bug
