### ISSUE TITLE
Double post protection (or ability to delete own message)

### ISSUE THREAD

**Issue by S-ed** [ludumdare/ludumdare#1445] opened 2017-12-04 05:33 UTC
Greetings.
I've posted a text and it posted twice (same content was in the post, now edited).
I'm not sure what was the cause but I assume there's no protection against that now (haven't tested, since there's no way to delete own post).

https://ldjam.com/events/ludum-dare/40/dungeon-chat-bot (here's topic it happened)

Thank you.

**Comment by povrazor** [comment] 2017-12-04 05:52
Heh, there's an almost comical history of this bug. It has come up many times in the dev chat channel, yet always at times when we're all too busy to do anything about it. Anyway, I'm glad there's an actual report now. :wink:

**Comment by mikekasprzak** [comment] 2018-05-26 18:02
Marking as duplicate of #1460.

**Closed by mikekasprzak** 2018-05-26 18:02 UTC
Labels: bug, duplicate
