### ISSUE TITLE
Session timeout occurs very quickly

### ISSUE THREAD

**Issue by pixlark** [ludumdare/ludumdare#574] opened 2017-04-11 00:48 UTC
Tabbed away from ldjam.com for probably 2 minutes, came back to a session timeout. Maybe this is by design, I don't know, just seems very short to me.

**Comment by povrazor** [comment] 2017-04-11 02:58
Not by design no. A bug. It just might have gotten worse after some software updates.

**Comment by karai17** [comment] 2017-04-11 04:02
I timed out while actively using the page...

**Comment by povrazor** [comment] 2017-04-11 04:43
I've set-up something that should fix it, I'm just putting it through its paces now.

In theory the "timeout while actively using" problem should be fixed now, but I need to see what happens if I don't use it for like an hour, if it's still persistent.

**Comment by karai17** [comment] 2017-04-11 04:44
It would be nice if time out just... didn't happen. There isn't really a
good reason to sign someone out unless they explicitly do so themselves.


---
Landon Manning
lmanning17@gmail.com

**Comment by povrazor** [comment] 2017-04-11 04:49
Definitely (security), but it can absolutely be bumped up to days instead of minutes.

The short timeout time is just a default setting for PHP. The server was also running 2 versions of PHP, and by default they share the same location of session data (`/tmp`), which sees them stomping all over each-other's expirations.

**Comment by povrazor** [comment] 2017-04-11 05:50
Excellent, it's working exactly as I expected (TTL gets reset any time you do something).

Now I'm going to drop the TTL very low (a couple minutes) just to confirm that I have control of it.

**Comment by povrazor** [comment] 2017-04-11 06:37
Okay, this should be solved now. There are going to be some other issues with login persistence, but those should be a separate bug.

**Closed** 2017-04-13 10:39 UTC
Labels: bug, To be closed
