### ISSUE TITLE
Same game twice?

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#1486] opened 2017-12-06 13:48 UTC
I just noticed that this game was published twice:
https://ldjam.com/users/mattcane/games

Edit:
Maybe same names should be forbidden if they are translated into the same unique URL?
"Attack of the Elvis" --> attack-of-the-elvis
"ATTACK :smiley: Of :smiley: The :smiley: Elvis" --> attack-of-the-elvis
Error: A game with this name already exists.
(But this would not prevent choosing "Attack of the fat Elvis")

**Comment by povrazor** [comment] 2017-12-06 18:30
That's a mixup. You'll note one is in the Jam and one has an X (unfinished). If you look at the URL, you'll notice they are different. We can't limit people's name choices, because it should not be a race to click the Publish button. We need to educate users to only click it if their game is done.

**Comment by pfefferminzz** [comment] 2017-12-06 22:52
You are right, i did not think about a rush for desired game names... that would be counterproductive indeed.

**Comment by pfefferminzz** [comment] 2017-12-09 12:22
But it's still the same game in the example. The unfinished game redirects to the finished game, because they were not able to delete the game page for the unfinished game.

**Comment by mikekasprzak** [comment] 2018-05-26 17:42
Marking as a duplicate of #1634 then.

**Closed by mikekasprzak** 2018-05-26 17:42 UTC
Labels: duplicate, to be closed
